server:
  port: 8001

# mysql
spring:
  application:
    name: auth-service
  datasource:
    password: 150621
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
# eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8701/eureka
