server:
  port: 8001

# mysql
spring:
  application:
    name: auth-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: 150621
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848/nacos