server:
  port: 8401

# spring
spring:
  application:
    name: search-service
  # mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: 150621
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  cloud:
    # nacos
    nacos:
      discovery:
        server-addr: localhost:8848
  # redis
  redis:
    database: 0
    url: redis://localhost:6379
    port: 6379
