# 自定义
msg:
  ver: 0.0.1

server:
  port: 8101

# mysql
spring:
  application:
    name: connection-service
  datasource:
    password: 150621
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  # redis
  redis:
    port: 6379
    url: redis://localhost:6379/
    database: 0