# 自定义
msg:
  ver: 0.0.1

server:
  port: 8101

# mysql
spring:
  datasource:
    password: 150621
    url: jdbc:mysql://localhost:3306/chat
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root