server:
  port: 8601

spring:
  application:
    name: user-service
  # mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: 150621
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&charset=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  cloud:
    # nacos
    nacos:
      discovery:
        server-addr: localhost:8848
  # redis
  redis:
    port: 6379
    url: redis://localhost:6379/
    database: 0
# mybatis
mybatis:
  mapper-locations: classpath:mybatis/*.xml # 映射文件位置
  type-aliases-package: com.ligen.entity # 别名配置
  type-handlers-package: com.ligen.handler
  configuration:
    use-generated-keys: true # 自增长主键
    map-underscore-to-camel-case: true # 驼峰下划线自动匹配
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# logging
logging:
  level:
    com.ligen.mapper: DEBUG