server:
  port: 8601

spring:
  application:
    name: user-service
  # mysql
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    password: 150621
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root


# mybatis
mybatis:
  mapper-locations: classpath:mybatis/*.xml # 映射文件位置
  #  config-location: classpath:mybatis/mybatis-config.xml # 核心配置文件位置
  type-aliases-package: com.ligen.entity # 别名配置
  configuration:
    use-generated-keys: true # 自增长主键
    map-underscore-to-camel-case: true # 驼峰下划线自动匹配

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8701/eureka